# Generated by Django 6.0.3 on 2026-03-10 21:10

import companys.models.business_location
import companys.models.company
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ext_id', models.TextField(default=companys.models.company.generate_company_ext_id, editable=False, max_length=255, unique=True, verbose_name='Company ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_company_name', violation_error_message='A company with this name already exists.')],
            },
        ),
        migrations.CreateModel(
            name='BussinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_location_ext_id', models.TextField(default=companys.models.business_location.generate_bussiness_location_ext_id, editable=False, max_length=255, unique=True, verbose_name='Business Location ID')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companys.company', verbose_name='Company')),
            ],
        ),
    ]
