# Generated by Django 6.0.3 on 2026-03-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bussiness_location_user_company'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BussinessLocation',
            new_name='BusinessLocation',
        ),
        migrations.RenameField(
            model_name='businesslocation',
            old_name='bussiness_location_ext_id',
            new_name='business_location_ext_id',
        ),
    ]
