# Generated by Django 6.0.3 on 2026-03-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bussiness_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companys.bussinesslocation', verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companys.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
